[project]
name = 'Decentralized-Energy-Efficiency-Credit'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credit-issuance]
path = 'contracts/credit-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-audit]
path = 'contracts/energy-audit.clar'
clarity_version = 2
epoch = 2.5

[contracts.trading]
path = 'contracts/trading.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
